from app.services.auth_service import (
    register_user,
    login_user,
    telegram_login,
    get_or_create_google_user,
)
from app.services.savings_service import (
    create_savings,
    get_savings,
    get_savings_by_id,
    update_savings,
    delete_savings,
    get_balance,
)
from app.services.loans_service import (
    create_loan,
    get_loans,
    get_loan_by_id,
    update_loan,
    delete_loan,
    add_payment,
    get_payments,
    get_total_active_loans_amount,
)
from app.services.targets_service import (
    create_target,
    get_targets,
    get_target_by_id,
    update_target,
    delete_target,
    get_total_target_current_amount,
)
from app.services.banks_service import (
    get_all_banks,
    get_bank_by_id,
    create_bank_account,
    get_bank_accounts,
    get_bank_account_by_id,
    update_bank_account,
    delete_bank_account,
)

__all__ = [
    "register_user",
    "login_user",
    "telegram_login",
    "get_or_create_google_user",
    "create_savings",
    "get_savings",
    "get_savings_by_id",
    "update_savings",
    "delete_savings",
    "get_balance",
    "create_loan",
    "get_loans",
    "get_loan_by_id",
    "update_loan",
    "delete_loan",
    "add_payment",
    "get_payments",
    "get_total_active_loans_amount",
    "create_target",
    "get_targets",
    "get_target_by_id",
    "update_target",
    "delete_target",
    "get_total_target_current_amount",
    "get_all_banks",
    "get_bank_by_id",
    "create_bank_account",
    "get_bank_accounts",
    "get_bank_account_by_id",
    "update_bank_account",
    "delete_bank_account",
]
